### ISSUE TITLE
pip install places vext.gi in wrong folder

### ISSUE THREAD

**Issue by MaZderMind** [stuaxo/vext#54]
installing `vext.gi` with pip 18.1 in a virtualenv created with 16.0.0 places the `gi.vext` file in `./env`, my virtualenv folder. moving it to `./env/share/vext/specs/gi.vext` makes vext find it. It seems the current version of `vext.gi` on pip, which is `0.7.0`, is broken in this combination.

Might be related to #52

**Comment by stuaxo** [comment]
I'm guessing the older virtualenv had an older version of vext.

This is probably WONTFIX due to the small amount of time I have, installing the current version of vext and any of the vext.* packages should fix it.

Feel free to reopen and paste in a script that reproduces the problem in a fresh virtualenv with current pip.

**Comment by MaZderMind** [comment]
I'm sorry to reopen this, but it is still happening with current pip 19.0.3 on virtualenv 16.4.3 with vext.gi 0.7.0 (all versions are the most recent):

```
/tmp virtualenv -ppython3 env 
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/env/bin/python3
Also creating executable in /tmp/env/bin/python
Installing setuptools, pip, wheel...done.

/tmp . ./env/bin/activate.fish 

(env) /tmp pip install vext.gi
Collecting vext.gi
Collecting vext>=0.7.0 (from vext.gi)
Collecting ruamel.yaml>=0.11.10 (from vext>=0.7.0->vext.gi)
  Using cached https://files.pythonhosted.org/packages/2a/e4/c29e64c0aa173cbb959d654982b5ed476a120f15ef75d5573ae60842eea1/ruamel.yaml-0.15.91-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: ruamel.yaml, vext, vext.gi
Successfully installed ruamel.yaml-0.15.91 vext-0.7.3 vext.gi-0.7.0

(env) /tmp python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/env/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 204, in load_module
    raise ImportError("No module named %s" % modulename)
ImportError: No module named gi
>>> 

(env) /tmp l env/gi.vext 
-rw-r--r-- 1 peter peter 445 Apr  7 23:06 env/gi.vext

(env) /tmp mkdir -p env/share/vext/specs
(env) /tmp mv env/gi.vext env/share/vext/specs/

(env) /tmp python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> 

(env) /tmp python3 -V
Python 3.6.7
(env) /tmp virtualenv --version
16.0.0
(env) /tmp pip --version
pip 19.0.3 from /tmp/env/lib/python3.6/site-packages/pip (python 3.6)
(env) /tmp 
```

**Comment by stuaxo** [comment]
Can you confirm its happening using the bash shell?

I've never tested the fish shell.

**Comment by MaZderMind** [comment]
I tested in a `debian:stretch` and `ubuntu:18.04` docker-container with `bash` and `fish` and was **unable to reproduce** the problem, so it probably isn't related to fish but caused by something locally on my installation.

I found that in these scenarios `vext.gi` will be placed at `env/gi.vext` **as well as** `env/share/vext/specs/vext.gi`.

Can you point me to the place in the install code, where `vext.gi` is moved/copied to in `share/vext/specs/`, so I can continue to debug the Problem on my machine?

**Comment by MaZderMind** [comment]
I was also **unable to reproduce** this on a clean Ubuntu 18.04 VM (which is what I'm using on my Systems, too) using either fish or bash as login-shell, so this is clearly is a problem within my specific environment.

**Comment by stuaxo** [comment]
OK, re-open if it happens again.

**Comment by justyn** [comment]
I've just seen exactly the same problem described, that the gi.vext file ended up in the root of my virtualenv dir. I had to move the file to `share/vext/specs/gi.vext` within the virtualenv to fix it.

vext 0.73

In case it is relevant, my virtualenvs directory is actually a symlink to a directory on a different drive.

**Comment by stuaxo** [comment]
Which OS are you using ?

**Comment by justyn** [comment]
I'm on Ubuntu 19.10.
pip 20.1
Python 3.7.5

**Comment by justyn** [comment]
FYI I've just seen this again on a new install of Ubuntu 20.04, using pipenv. I'm using the default virtualenv directory this time, no strange configuration to explain it.

pip 20.1.1
python 3.8.2

**Comment by stuaxo** [comment]
To help me reproduce it, can you write the exact commands you use to create the virtualenv with pipenv + install venv.

I think, things are getting muddied on my end because I'm either installing a different version or in a different way.

**Comment by stuaxo** [comment]
The code to copy vext files to the virtualenv is here -
https://github.com/stuaxo/vext/blob/master/vext/install/__init__.py#L60

**Comment by justyn** [comment]
Sure, I just ran these commands in a new, empty directory:

```
pipenv --python 3.8
pipenv shell
pip install vext
pip install vext.gi
```
This appears to be successful.
Afterwards this is the contents of the virtualenv directory:

```
bin  gi.vext  lib  pyvenv.cfg  share
```

note that gi.vext shouldn't be there.

**Comment by justyn** [comment]
It may be a separate issue, but I've found I get an error if I try to install vext.gi with `pipenv install`.
These commands:

```
pipenv --python 3.8
pipenv install vext
pipenv install vext.gi
```

The last command throws an error, here's a dump of the output:

```
Installing vext.gi…
Error:  An error occurred while installing vext.gi!
Error text: Collecting vext.gi
  Using cached vext.gi-0.7.0.tar.gz (2.8 kB)
Requirement already satisfied, skipping upgrade: vext>=0.7.0 in /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/lib/python3.8/site-packages (from vext.gi->-r /tmp/pipenv-2b1thais-requirements/pipenv-3txhwdp_-requirement.txt (line 1)) (0.7.3)
Requirement already satisfied, skipping upgrade: ruamel.yaml>=0.11.10 in /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/lib/python3.8/site-packages (from vext>=0.7.0->vext.gi->-r /tmp/pipenv-2b1thais-requirements/pipenv-3txhwdp_-requirement.txt (line 1)) (0.16.10)
Requirement already satisfied, skipping upgrade: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/lib/python3.8/site-packages (from ruamel.yaml>=0.11.10->vext>=0.7.0->vext.gi->-r /tmp/pipenv-2b1thais-requirements/pipenv-3txhwdp_-requirement.txt (line 1)) (0.2.0)
Building wheels for collected packages: vext.gi
  Building wheel for vext.gi (setup.py): started
  Building wheel for vext.gi (setup.py): finished with status 'error'
  Running setup.py clean for vext.gi
Failed to build vext.gi
Installing collected packages: vext.gi
    Running setup.py install for vext.gi: started
    Running setup.py install for vext.gi: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yy5eszro/vext.gi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yy5eszro/vext.gi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z2klkegv
       cwd: /tmp/pip-install-yy5eszro/vext.gi/
  Complete output (26 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  vext.gi Install
  running install_data
  creating build
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/vext.gi-0.7.0.data
  creating build/bdist.linux-x86_64/wheel/vext.gi-0.7.0.data/data
  copying gi.vext -> build/bdist.linux-x86_64/wheel/vext.gi-0.7.0.data/data/
  running install_egg_info
  running egg_info
  writing vext.gi.egg-info/PKG-INFO
  writing dependency_links to vext.gi.egg-info/dependency_links.txt
  writing requirements to vext.gi.egg-info/requires.txt
  writing top-level names to vext.gi.egg-info/top_level.txt
  reading manifest file 'vext.gi.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.txt'
  writing manifest file 'vext.gi.egg-info/SOURCES.txt'
  Copying vext.gi.egg-info to build/bdist.linux-x86_64/wheel/vext.gi-0.7.0-py3.8.egg-info
  running install_scripts
  Install vext files:
  error: [Errno 2] No such file or directory: 'vext'
  ----------------------------------------
  ERROR: Failed building wheel for vext.gi
    ERROR: Command errored out with exit status 1:
     command: /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yy5eszro/vext.gi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yy5eszro/vext.gi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eecn2dh1/install-record.txt --single-version-externally-managed --compile --install-headers /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/include/site/python3.8/vext.gi
         cwd: /tmp/pip-install-yy5eszro/vext.gi/
    Complete output (20 lines):
    running install
    vext.gi Install
    running build
    running install_data
    copying gi.vext -> /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/
    running install_egg_info
    running egg_info
    writing vext.gi.egg-info/PKG-INFO
    writing dependency_links to vext.gi.egg-info/dependency_links.txt
    writing requirements to vext.gi.egg-info/requires.txt
    writing top-level names to vext.gi.egg-info/top_level.txt
    reading manifest file 'vext.gi.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.txt'
    writing manifest file 'vext.gi.egg-info/SOURCES.txt'
    Copying vext.gi.egg-info to /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/lib/python3.8/site-packages/vext.gi-0.7.0-py3.8.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-record-eecn2dh1/install-record.txt'
    Install vext files:
    error: [Errno 2] No such file or directory: 'vext'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yy5eszro/vext.gi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yy5eszro/vext.gi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eecn2dh1/install-record.txt --single-version-externally-managed --compile --install-headers /home/justyn/.local/share/virtualenvs/testvext3-U9tvAjbl/include/site/python3.8/vext.gi Check the logs for full command output.

✘ Installation Failed 
```

**Comment by justyn** [comment]
@stuaxo when should install_vexts be being called?

I dropped some print statements in there (in the version in the virtualenv) as a quick check and got nothing out when running `pip install vext.gi`, but not knowing enough about how pip operates, that might not be expected anyway.

**Comment by stuaxo** [comment]
Thanks, the output is really useful.

Each package (e.g. vext.gi) has a post_install action that calls `vext -i` to install the "vext" file(s).
It's done this way to work around pips  sandbox, so is fragile.

https://github.com/stuaxo/vext.gi/blob/master/setup.py#L28
https://github.com/stuaxo/vext.gi/blob/master/setup.py#L46

If this call to vext used the full path it might be better, e.g. the virtualenv dir/bin/vext

**Comment by stuaxo** [comment]
I managed to reproduce the issue of the .vext files being installed to the wrong place at least :)

vext + pipenv didn't want to play together so I had to disable vext during install:

```
$ VEXT_DISABLED=1 pipenv install vext
$ VEXT_DISABLED=1 pipenv install vext.gi
```

Still needs a little bit more debugging to see whats happening to the file paths.

**Comment by stuaxo** [comment]
OK, vext files should be installed in the correct place in 0.7.4 just released (I think there may be a bonus copy in the wrong place too for now, but this is progress).

**Comment by justyn** [comment]
Amazing, I tried using `pip install vext.gi` in a new pipenv, and it correctly installed gi.vext in the right place, no duplicate copy either. Thanks!

`pipenv install vext.gi` still throws: `error: [Errno 2] No such file or directory: 'vext'`

**Comment by stuaxo** [comment]
Great :) it seems a combo of a small fix I out in plus newer pipenv have this working.

I will need to add pipenv to the integration tests to keep it working.
